1.19 Port
lorddusk/HQM pull request #662
Opened 2022-08-24 05:06 UTC by CodexAdrian

This PR ports HQM to 1.19 and removes all references to Lib Block attributes, replacing them with the Fabric Transfer Api, as well as replacing the Fluidstacks with the Architectury Fluidstack object

2022-08-24 21:35 UTC, kirderf1 requested changes

2022-08-24 21:35 UTC, kirderf1 commented on fabric/build.gradle
> +    modImplementation 'TechReborn:TechReborn-1.19:+'
How about using `modRuntimeOnly` for these dependencies?

2022-08-24 21:35 UTC, kirderf1 commented on fabric/gradle.properties
> +lba=0.11.0-+
lba is no longer a dependency, so you can remove this version definition

2022-08-24 21:35 UTC, kirderf1 commented on fabric/src/main/java/hardcorequesting/fabric/tileentity/QSDFluidTank.java
> +    public long extract(FluidVariant resource, long maxAmount, TransactionContext transaction) {
`extract()` and `supportsExtraction()` are already implemented like this in `InsertionOnlyStorage`, so these overrides are not needed.

2022-08-24 21:35 UTC, kirderf1 commented on fabric/src/main/java/hardcorequesting/fabric/tileentity/QSDFluidTank.java
> +            if (task.increaseFluid(fluidStack, blockEntity.getPlayerUUID(), true)) {
With this current implementation, any fluid insertions will automatically be committed regardless of if the transaction is committed or aborted. This is not good.

2022-08-24 21:35 UTC, kirderf1 commented on forge/src/main/java/hardcorequesting/forge/BookCatalystRecipeSerializer.java
> -public class BookCatalystRecipeSerializer extends ForgeRegistryEntry<RecipeSerializer<?>> implements RecipeSerializer<BookCatalystRecipe> {
With this change, this serializer should be equivalent to its fabric counterpart, and can be moved to the common project.

2022-08-24 21:35 UTC, kirderf1 commented on forge/src/main/java/hardcorequesting/forge/HardcoreQuestingForge.java
> +    //Todo come back to this
`registerOnHudRender()` appears to be unused in recent versions of HQM. Perhaps you could resolve this todo by removing the function?

2022-08-24 21:35 UTC, kirderf1 commented on forge/src/main/resources/META-INF/mods.toml
> +modId = "minecraft"
I don't think this mod id is supposed to be "minecraft"

2022-08-24 22:13 UTC, CodexAdrian commented on fabric/src/main/java/hardcorequesting/fabric/tileentity/QSDFluidTank.java
> +            if (task.increaseFluid(fluidStack, blockEntity.getPlayerUUID(), true)) {
Looks like you're right. I think the only way to solve this would be to make the tank state aware, the api seems to work by actually performing the action on simulation and then reverting the state back to the old state before the transaction started. I honestly don't really know how you would store the current state of a quest task so you can revert it back, I'll look into it

2022-08-24 23:39 UTC, CodexAdrian commented on fabric/src/main/java/hardcorequesting/fabric/tileentity/QSDFluidTank.java
> +            if (task.increaseFluid(fluidStack, blockEntity.getPlayerUUID(), true)) {
I implemented this, seems to work, sort of hard to tell if simulation is working but everything still performs as expected, i think i'll mark this is as resolved

2022-08-25 12:26 UTC, kirderf1 requested changes

2022-08-25 12:26 UTC, kirderf1 commented on fabric/src/main/java/hardcorequesting/fabric/tileentity/QSDFluidTank.java
> +            task.increaseFluid(fluidStack, blockEntity.getPlayerUUID(), true);
`increaseFluid()` can call `doCompletionCheck()`, which I believe should only get called when the transaction has committed.

2022-08-25 12:26 UTC, kirderf1 commented on fabric/src/main/java/hardcorequesting/fabric/tileentity/QSDFluidTank.java
> +public class QSDFluidTank extends SnapshotParticipant<QSDFluidTank.FluidQuestData> implements InsertionOnlyStorage<FluidVariant> {
Could you write a javadoc on the`is class that gives an overview on how this fluid tank works?

2022-08-25 19:49 UTC, kirderf1 approved these changes
Before this PR when I first looked at using fabrics transfer api myself, I was a bit worried that tracking snapshots in an object attached to the block entity and not to the quest task data might cause issues with multiple block entities targeting the same quest task.

However looking at it again while reviewing this PR, I've learned that in the case of an aborted transaction, snapshots are explicitly applied in the opposite order that they were created.
As such, snapshots across multiple `QDSFluidStack`s should not be able to interfere with each other to cause issues, even when targeting the same quest task data.

2022-08-25 19:54 UTC, merged